INSERT INTO repertorio
(titulo, artista, tom, bpm, link_youtube, link_spotify, observacoes, ultimo_uso, criado_em, criado_por_id)
VALUES
('A Ele a Glória', 'Gabriela Rocha', 'F', NULL, 'https://www.youtube.com/watch?v=9p3qBC3VotM', NULL, 'Adoração', NULL, NOW(), NULL),
('Nada Pode Calar um Adorador', 'Eyshila', 'G', NULL, 'https://www.youtube.com/watch?v=rDhJTDVZ1cI', NULL, 'Adoração', NULL, NOW(), NULL),
('Agnus Dei', 'David Quinlan', 'F', NULL, 'https://www.youtube.com/watch?v=B3Tkoa76ZMc', NULL, 'Adoração', NULL, NOW(), NULL),
('Algo Novo', 'Kemuel', 'F', NULL, 'https://www.youtube.com/watch?v=wWU1Bn6wy9o', NULL, 'Adoração', NULL, NOW(), NULL),
('Alvo Mais que a Neve', 'Harpa Cristã', 'C', NULL, 'https://www.youtube.com/watch?v=js3nRTVB-fg', NULL, 'Santa Ceia', NULL, NOW(), NULL),
('Amigo Espírito Santo', 'Cassiane', 'F', NULL, 'https://www.youtube.com/watch?v=uuOIiyATSCc', NULL, 'Adoração', NULL, NOW(), NULL),
('Além do Impossível', 'Felipe Rodrigues', 'E', NULL, 'https://www.youtube.com/watch?v=AqMVEVKRSoQ', NULL, 'Adoração', NULL, NOW(), NULL),
('Arde Outra Vez', 'Thalles Roberto', 'F#m', NULL, 'https://www.youtube.com/watch?v=_pnAJPnp_Jw', NULL, 'Adoração', NULL, NOW(), NULL),
('Até que o Senhor Venha', 'Ministério Zoe', 'E', NULL, 'https://www.youtube.com/watch?v=TdMS20oszR4', NULL, 'Adoração', NULL, NOW(), NULL),
('Bem Mais que Tudo', 'Aline Barros', 'E', NULL, 'https://www.youtube.com/watch?v=tG0ZM8xqAhg', NULL, 'Santa Ceia', NULL, NOW(), NULL),
('Porque Ele Vive', 'Harpa Cristã', 'E', NULL, 'https://www.youtube.com/watch?v=sFOmIAYCMEM', NULL, 'Ofertório', NULL, NOW(), NULL),
('Caminho no Deserto', 'Soraya Moraes', 'G', NULL, 'https://www.youtube.com/watch?v=AAvjEp7u9tA', NULL, 'Adoração', NULL, NOW(), NULL),
('Campeões da Luz', 'Harpa Cristã', 'A', NULL, 'https://www.youtube.com/watch?v=uFXPTEe3IAM', NULL, 'Abertura', NULL, NOW(), NULL),
('Canção do Apocalipse', 'Diante do Trono', 'E', NULL, 'https://www.youtube.com/watch?v=5j0arvaKdqk', NULL, 'Adoração', NULL, NOW(), NULL),
('Clamo Jesus', 'Paulo César Baruk', 'E', NULL, 'https://www.youtube.com/watch?v=ye9caqETC0A', NULL, 'Adoração', NULL, NOW(), NULL),
('Com Muito Louvor', 'Cassiane', 'G', NULL, 'https://www.youtube.com/watch?v=440SucDfC2Y', NULL, 'Adoração', NULL, NOW(), NULL),
('Cordeiro e Leão', 'Jefferson & Suellen', 'D', NULL, 'https://www.youtube.com/watch?v=SKS7zkEEqrM', NULL, 'Adoração', NULL, NOW(), NULL),
('De Graça em Graça', 'Hillsong Worship', 'B', NULL, 'https://www.youtube.com/watch?v=SMRN-uXRQmc', NULL, 'Solo', NULL, NOW(), NULL),
('Deus de Obras Completas', 'Kemilly Santos', 'G', NULL, 'https://www.youtube.com/watch?v=Ds200TtR97o', NULL, 'Adoração', NULL, NOW(), NULL),
('Deus Forte', 'Kleber Lucas', 'B', NULL, 'https://www.youtube.com/watch?v=Raerz_GTr4E', NULL, 'Adoração', NULL, NOW(), NULL),
('Deus Tremendo', 'Shirley Carvalhaes', 'G', NULL, 'https://www.youtube.com/watch?v=uaZY4Q1EPP8', NULL, 'Abertura', NULL, NOW(), NULL),
('Diante da Cruz', 'Aline Barros', 'D', NULL, 'https://youtu.be/Uo_0wr_iXJg', NULL, 'Adoração', NULL, NOW(), NULL),
('Dias de Elias', 'Lauriete', 'D', NULL, 'https://youtu.be/foLsTR4YF9U', NULL, 'Abertura', NULL, NOW(), NULL),
('Emaús', 'Morada', 'D', NULL, 'https://youtu.be/d7iMVvuZkyg', NULL, 'Adoração', NULL, NOW(), NULL),
('Enche-me', 'Gabriela Rocha', 'F', NULL, 'https://www.youtube.com/watch?v=ozBlvwVizXI', NULL, 'Adoração', NULL, NOW(), NULL),
('Ensina o Menino', 'Michele do Pandeiro', 'F', NULL, 'https://www.youtube.com/watch?v=sDefRlVkZ3Y', NULL, 'Pós-ceia', NULL, NOW(), NULL),

('Escudo', NULL, 'D', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Estamos de Pé', NULL, 'C', NULL, NULL, NULL, 'Abertura', NULL, NOW(), NULL),
('Eu Sou Teu', NULL, 'F', NULL, NULL, NULL, 'Ofertório', NULL, NOW(), NULL),
('Eu Vejo a Glória', NULL, 'G', NULL, NULL, NULL, 'Ofertório', NULL, NOW(), NULL),
('Fale com Jesus', NULL, 'G/F', NULL, NULL, NULL, 'Solo', NULL, NOW(), NULL),
('Filho do Deus Vivo', NULL, 'E', NULL, 'https://youtu.be/PdJoTcOgwUA', NULL, 'Abertura', NULL, NOW(), NULL),
('Galileu', NULL, 'F#', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Grande é o Senhor', NULL, 'F', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Lindo Momento', NULL, 'D', NULL, 'https://youtu.be/xcC3Xh3PFcE', NULL, 'Adoração', NULL, NOW(), NULL),
('Mil Graus', NULL, 'C', NULL, NULL, NULL, 'Abertura', NULL, NOW(), NULL),
('Meu Deus é Grande', NULL, 'G', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Nossa Esperança', 'Harpa Cristã', 'D', NULL, NULL, NULL, 'Ofertório', NULL, NOW(), NULL),
('Nada Mais', NULL, 'F', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Obras Completas', NULL, 'G', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('O Grande', NULL, 'C', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Os Guerreiros', NULL, 'E', NULL, NULL, NULL, 'Abertura', NULL, NOW(), NULL),
('Palavras', NULL, 'E', NULL, NULL, NULL, 'Solo', NULL, NOW(), NULL),
('Plena Paz', 'Harpa Cristã', 'D', NULL, NULL, NULL, 'Ofertório', NULL, NOW(), NULL),
('Preciso de Ti', NULL, 'F', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Questiona ou Adora', NULL, 'C', NULL, NULL, NULL, 'Solo', NULL, NOW(), NULL),
('Santo pra Sempre', NULL, 'E', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Se Eu Não Te Ouvir', NULL, 'C', NULL, NULL, NULL, 'Solo', NULL, NOW(), NULL),
('Solta o Cabo da Nau', 'Harpa Cristã', 'A', NULL, NULL, NULL, 'Ofertório', NULL, NOW(), NULL),
('Sobrevivi', NULL, 'G', NULL, NULL, NULL, 'Ofertório', NULL, NOW(), NULL),
('Só Quero Tua Presença', NULL, 'C', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Só Tu És Santo', NULL, 'C', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Te Agradeço', 'Diante do Trono', 'C', NULL, NULL, NULL, 'Solo', NULL, NOW(), NULL),
('Te Adorar Senhor é o Meu Prazer', NULL, 'D', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Teu Amor Não Falha', NULL, 'C', NULL, 'https://youtu.be/3q-pRKf-VaQ', NULL, 'Adoração', NULL, NOW(), NULL),
('Tudo é Perda', NULL, 'E', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Um Novo Dia', NULL, 'G', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Videira', NULL, 'C', NULL, NULL, NULL, 'Abertura', NULL, NOW(), NULL),
('Vencendo Vem Jesus', 'Harpa Cristã', 'E', NULL, NULL, NULL, 'Pós-ceia', NULL, NOW(), NULL),
('Vitorioso És', NULL, 'A/F', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL),
('Vou Te Alegrar', NULL, 'E', NULL, NULL, NULL, 'Ofertório', NULL, NOW(), NULL),
('Yahweh se Manifestará', NULL, 'G', NULL, NULL, NULL, 'Adoração', NULL, NOW(), NULL);